spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.153.130:8848
    alicloud:
      access-key: LTAI5tAj7JgXViru9GhUhaCh
      secret-key: 3TcvJXYSy6IaSZOjgCwORQA4Z0SCxG
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: qlq-mall
    application:
      name: mall-third
server:
  port: 8090
