spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.153.178:8848
    alicloud:
      access-key: LTAI5tAj7JgXViru9GhUhaCh
      secret-key: 3TcvJXYSy6IaSZOjgCwORQA4Z0SCxG
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: qlq-mall
      # 短信验证服务参数配置
      sms:
        host: https://dfsns.market.alicloudapi.com
        path: /data/send_sms
        method: POST
        appCode: 8bbf0cda1bfa4430a3c1776134aa3806
    application:
      name: mall-third
server:
  port: 8090
