# 数据库的连接新
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.153.130:3306/mall-oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.153.178:8848
  application:
    name: mall-order
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  session:
    store-type: redis
    redis:
      namespace: spring:session
    timeout: 30m
  redis:
    host: 192.168.153.178
    port: 6379
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto # 主键自增

server:
  port: 8030

user:
  name: zhangSan
  age: 18

rocketmq:
  name-server: 192.168.153.178:9876
  producer:
    group: order-producer
  consumer:
    group: order-consumer